### ISSUE TITLE
probleme d'ouverture de /tmp/SQL et /tmp/PTT avec python3.9

### ISSUE THREAD

**Issue by f5nlg** [armel/SpotnikContrib#3]
./svxbridge.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/SQL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/etc/svxlink/svxbridge/./svxbridge.py", line 36, in <module>
    ser = serial.Serial('/tmp/SQL')
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /tmp/SQL: [Errno 2] No such file or directory: '/tmp/SQL'

pyserial et python3-pyaudio sont installé .

**Comment by f5nlg** [comment]
probleme svxlink ?
